In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
df=pd.read_csv("/content/Iris 8.csv")
print(df.head(10))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa


In [ ]:
features=df.iloc[:,1:5]
print(features.head(5))

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2


In [ ]:
labels=df.iloc[:,5]
print(labels.head(5))

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test=train_test_split(features, labels, test_size=0.2, random_state=0)
print(features_train.info)
print(features_test.info)
print(labels_train)
print(labels_test)

<bound method DataFrame.info of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137            6.4           3.1            5.5           1.8
84             5.4           3.0            4.5           1.5
27             5.2           3.5            1.5           0.2
127            6.1           3.0            4.9           1.8
132            6.4           2.8            5.6           2.2
..             ...           ...            ...           ...
9              4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
67             5.8           2.7            4.1           1.0
117            7.7           3.8            6.7           2.2
47             4.6           3.2            1.4           0.2

[120 rows x 4 columns]>
<bound method DataFrame.info of      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
114            5.8           2.8            5.1           2.4
62             6.0           2.2           

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
sc=StandardScaler()
sc.fit(features_train)
features_train_std=sc.transform(features_train)
features_test_std=sc.transform(features_test)
print(features_train_std)
print(features_test_std)

[[ 0.61303014  0.10850105  0.94751783  0.73603967]
 [-0.56776627 -0.12400121  0.38491447  0.34808318]
 [-0.80392556  1.03851009 -1.30289562 -1.3330616 ]
 [ 0.25879121 -0.12400121  0.60995581  0.73603967]
 [ 0.61303014 -0.58900572  1.00377816  1.25331499]
 [-0.80392556 -0.82150798  0.04735245  0.21876435]
 [-0.21352735  1.73601687 -1.19037495 -1.20374277]
 [ 0.14071157 -0.82150798  0.72247648  0.47740201]
 [ 0.02263193 -0.12400121  0.21613346  0.34808318]
 [-0.09544771 -1.05401024  0.10361279 -0.03987331]
 [ 1.0853487  -0.12400121  0.94751783  1.12399616]
 [-1.39432376  0.34100331 -1.41541629 -1.3330616 ]
 [ 1.20342834  0.10850105  0.72247648  1.38263382]
 [-1.04008484  1.03851009 -1.24663528 -0.81578628]
 [-0.56776627  1.50351461 -1.30289562 -1.3330616 ]
 [-1.04008484 -2.4490238  -0.1776889  -0.29851096]
 [ 0.73110978 -0.12400121  0.94751783  0.73603967]
 [ 0.96726906  0.57350557  1.0600385   1.64127148]
 [ 0.14071157 -1.98401928  0.66621615  0.34808318]
 [ 0.96726906 -1.2865125   1.11

Support Vector Classifier

In [ ]:
from sklearn.svm import SVC
svm=SVC(kernel='rbf', random_state=0, gamma=.10, C=1.0)
svm.fit(features_train_std, labels_train)
print("The accuracy of SVC on training data is {:.2f}".format(svm.score(features_train_std,labels_train)))
print("The accuracy of SVC on testing data is {:.2f}".format(svm.score(features_test_std, labels_test)))

The accuracy of SVC on training data is 0.97
The accuracy of SVC on testing data is 1.00


KNN Classifier(K nearest Neighbors)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7, p=2, metric="minkowski")
knn.fit(features_train_std, labels_train)
print("The accuracy of KNN Classifier on training data is {:.2f}".format(svm.score(features_train_std, labels_train)))
print("The accuracy of KNN Classifier on testing data is {:.2f}".format(svm.score(features_test_std, labels_test)))

The accuracy of KNN Classifier on training data is 0.97
The accuracy of KNN Classifier on testing data is 1.00


XGBoost Classifier

In [ ]:
import xgboost as xgb
xgb_cl=xgb.XGBClassifier()
xgb_cl=xgb_cl.fit(features_train_std, labels_train)
print("The accuracy of XGBoost Classifier on training data is {:.2f}".format(xgb_cl.score(features_train_std, labels_train)))
print("The accuracy of XGBoost Classifier on testing data is {:.2f}".format(xgb_cl.score(features_test_std, labels_test)))

The accuracy of XGBoost Classifier on training data is 1.00
The accuracy of XGBoost Classifier on testing data is 1.00


Decision Tree

In [ ]:
from sklearn import tree
decision_tree=tree.DecisionTreeClassifier(criterion="gini")
decision_tree.fit(features_train_std,labels_train)
print("The accuracy of Decision Tree Classifier on training data is {:.2f}".format(decision_tree.score(features_train_std, labels_train)))
print("The accuracy of Decision Tree Classifier on testin data is {:.2f}".format(decision_tree.score(features_test_std, labels_test)))

The accuracy of Decision Tree Classifier on training data is 1.00
The accuracy of Decision Tree Classifier on testin data is 1.00


Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_forest=RandomForestClassifier()
random_forest.fit(features_train_std,labels_train)
print("The accuracy of Random Forest Classifier on training data is {:.2f}".format(random_forest.score(features_train_std, labels_train)))
print("The accuracy of Random Forest Classifier on testing data is {:.2f}".format(random_forest.score(features_test_std, labels_test)))

The accuracy of Random Forest Classifier on training data is 1.00
The accuracy of Random Forest Classifier on testing data is 1.00


EDA

1. Scatterplot

In [ ]:
from sklearn.datasets import load_iris

iris=load_iris()
features_All=[]
features1= iris.data[:, [0,1,2,3]]
features1.shape
print(features1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.